### ISSUE TITLE
permalink issue after sync to jekyll

### ISSUE THREAD

**Issue by riichiie** [benbalter/wordpress-github-sync#67] opened 2015-05-18 06:32 UTC
after sync , the permalink of post defined in the front matter block, is exactly the same with the permalink in wordpress.

**Comment by mAAdhaTTah** [comment] 2015-05-18 11:46
They're supposed to be? Unless that's a typo. :) Got an example?

**Comment by riichiie** [comment] 2015-05-18 12:55
on my pages, http://riichiie.github.io/http:/www.riichiie.net/2015/05/test-sync-to-github//

the link is supposed to http://riichiie.github.io/2015/05/test-sync-to-github/

**Comment by mAAdhaTTah** [comment] 2015-05-18 14:06
The permalink in the frontmatter is the permalink from the WordPress source, not the Jekyll destination. You can use the [`wpghs_post_meta`](https://github.com/benbalter/wordpress-github-sync/blob/master/lib/post.php#L315) filter to overwrite this behavior if you want a different permalink.

**Comment by mAAdhaTTah** [comment] 2015-05-18 23:23
Closing, as this is intended behavior. Let me know if you're still need help though.

**Closed by mAAdhaTTah** 2015-05-18 23:23 UTC
